console.log(Boolean(str))
console.log(!!str)
console.log(Boolean(false))
console.log(Boolean(''))
console.log(Boolean(NaN))
console.log(Boolean(undefined))
console.log(Boolean(0))
console.log(Boolean(null))

console.log(Boolean(-1))
console.log(Boolean(85))