const albums = [
  {
    title: 'album 1',
    name: 'Katy Perry',
    img: './img/artist_1.png',
  },
  {
    title: 'album 2',
    name: 'Taylor Swift',
    img: './img/artist_2.png',
  },
  {
    title: 'album 3',
    name: 'Imagine Dragons',
    img: './img/artist_3.png',
  },
  {
    title: 'album 4',
    name: 'Justin Bieber',
    img: './img/artist_4.png',
  },
  {
    title: 'album 5',
    name: 'Marshmello',
    img: './img/artist_5.png',
    src: './music/Katy Perry - Roulette.mp3',
  },
];

const songs = [
  {
    artist: 'Katy Perry',
    name: 'Roulette',
    img: './img/artist_1.png',
    duration: '3:50',
    src: './music/Katy Perry - Roulette.mp3',
  },
  {
    artist: 'Katy Perry',
    name: 'Rise',
    img: './img/artist_1.png',
    duration: '3:09',
    src: './music/Katy Perry - Rise.mp3',
  },
  {
    artist: 'Katy Perry',
    name: 'Never Really Over',
    img: './img/artist_1.png',
    duration: '4:25',
    src: './music/Katy Perry - Never Really Over.mp3',
  },
  {
    artist: 'Katy Perry',
    name: 'I Kissed A Girl',
    img: './img/artist_1.png',
    duration: '3:28',
    src: './music/Katy Perry - I Kissed A Girl.mp3',
  },
  {
    artist: 'Katy Perry',
    name: 'Firework',
    img: './img/artist_1.png',
    duration: '3:50',
    src: './music/Katy Perry - Firework.mp3',
  },
  {
    artist: 'Taylor Swift',
    name: 'Blank Space',
    img: './img/artist_2.png',
    duration: '2:45',
    src: './music/Taylor Swift - Blank Space.mp3',
  },
  {
    artist: 'Taylor Swift',
    name: 'Love Story',
    img: './img/artist_2.png',
    duration: '3:34',
    src: './music/Taylor Swift - Love Story.mp3',
  },
  {
    artist: 'Taylor Swift',
    name: 'Shake It Off',
    img: './img/artist_2.png',
    duration: '3:54',
    src: './music/Taylor Swift - Shake It Off.mp3',
  },
  {
    artist: 'Taylor Swift',
    name: 'The Archer',
    img: './img/artist_2.png',
    duration: '3:20',
    src: './music/Taylor Swift - The Archer.mp3',
  },
  {
    artist: 'Taylor Swift',
    name: 'Happier',
    img: './img/artist_2.png',
    duration: '3:20',
    src: './music/Taylor Swift - Wildest Dreams.mp3',
  },
  {
    artist: 'Imagine Dragons',
    name: 'Bad Liar',
    img: './img/artist_3.png',
    duration: '3:46',
    src: './music/Imagine Dragons - Bad Liar.mp3',
  },
  {
    artist: 'Imagine Dragons',
    name: 'Believer',
    img: './img/artist_3.png',
    duration: '3:45',
    src: './music/Imagine Dragons - Believer.mp3',
  },
  {
    artist: 'Imagine Dragons',
    name: 'Natural',
    img: './img/artist_3.png',
    duration: '4:57',
    src: './music/Imagine Dragons - Natural.mp3',
  },
  {
    artist: 'Imagine Dragons',
    name: 'Thunder',
    img: './img/artist_3.png',
    duration: '3:30',
    src: './music/Imagine Dragons - Thunder.mp3',
  },
  {
    artist: 'Imagine Dragons',
    name: 'Whatever It Takes',
    img: './img/artist_3.png',
    duration: '3:54',
    src: './music/Imagine Dragons - Whatever It Takes.mp3',
  },
  {
    artist: 'Justin Bieber',
    name: 'Boyfriend',
    img: './img/artist_4.png',
    duration: '3:24',
    src: './music/Justin Bieber - Boyfriend.mp3',
  },
  {
    artist: 'Justin Bieber',
    name: 'Company',
    img: './img/artist_4.png',
    duration: '3:05',
    src: './music/Justin Bieber - Company.mp3',
  },
  {
    artist: 'Justin Bieber',
    name: 'Hold On',
    img: './img/artist_4.png',
    duration: '3:20',
    src: './music/Justin Bieber - Hold On.mp3',
  },
  {
    artist: 'Justin Bieber',
    name: 'Sorry',
    img: './img/artist_4.png',
    duration: '3:26',
    src: './music/Justin Bieber - Sorry.mp3',
  },
  {
    artist: 'Justin Bieber',
    name: 'Yummy',
    img: './img/artist_4.png',
    duration: '3:45',
    src: './music/Justin Bieber - Yummy.mp3',
  },
  {
    artist: 'Marshmello',
    name: 'Alone',
    img: './img/artist_5.png',
    duration: '3:21',
    src: './music/Marshmello - Alone.mp3',
  },
  {
    artist: 'Marshmello',
    name: 'Moving On',
    img: './img/artist_5.png',
    duration: '3:52',
    src: './music/Marshmello - Moving On.mp3',
  },
  {
    artist: 'Marshmello',
    name: 'Together',
    img: './img/artist_5.png',
    duration: '3:13',
    src: './music/Marshmello - Together.mp3',
  },
  {
    artist: 'Marshmello',
    name: 'Friends',
    img: './img/artist_5.png',
    duration: '3:45',
    src: './music/Marshmello & Anne-Marie - Friends.mp3',
  },
  {
    artist: 'Marshmello',
    name: 'Happier',
    img: './img/artist_5.png',
    duration: '3:52',
    src: './music/Marshmello & Bastille - Happier.mp3',
  },
];
