const ALL_ITEMS = [
    {
        album: 1,
        cover_album: './images/alan_walker.png',        
        songs: [
            {
                id: 1,
                cover: "./images/Alan_Walker_-_Alone.png",
                artist: "Alan Walker",
                title: "Alone",
                length: '2:40',
                src: "./songs/alan_walker_-_alone.mp3",
            },            
            {
                id: 2,
                cover: "./images/alan_walker_-_catch_me_if_you_can.jpg",
                artist: "Alan Walker",
                title: "Catch me if you can",
                length: '2:31',
                src: "./songs/alan_walker_-_catch_me_if_you_can.mp3",
            },
            {
                id: 3,
                cover: "./images/alan_walker_-_faded.jpg",
                artist: "Alan Walker",
                title: "Faded",
                length: '3:32',
                src: "./songs/alan_walker_-_faded.mp3",
            },
            {
                id: 4,
                cover: "./images/alan_walker_-_the_drum.jpg",
                artist: "Alan Walker",
                title: "The drum",
                length: '3:09',
                src: "./songs/alan_walker_-_the_drum.mp3",
            },
            {
                id: 5,
                cover: "./images/alan_walker_-_the_spectre.jpg",
                artist: "Alan Walker",
                title: "The spectre",
                length: '3:13',
                src: "./songs/alan_walker_-_the_spectre.mp3",
            },
            {
                id: 6,
                cover: "./images/alan_walker_-_unity.jpg",
                artist: "Alan Walker",
                title: "Unity",
                length: '3:24',
                src: "./songs/alan_walker_-_unity.mp3",
            },
            {
                id: 7,
                cover: "./images/Alan_Walker_-_Alone.png",
                artist: "Alan Walker",
                title: "Alone",
                length: '2:40',
                src: "./songs/alan_walker_-_alone.mp3",
            },
            {
                id: 8,
                cover: "./images/alan_walker_-_catch_me_if_you_can.jpg",
                artist: "Alan Walker",
                title: "Catch me if you can",
                length: '2:31',
                src: "./songs/alan_walker_-_catch_me_if_you_can.mp3",
            },
            {
                id: 9,
                cover: "./images/alan_walker_-_faded.jpg",
                artist: "Alan Walker",
                title: "Faded",
                length: '3:32',
                src: "./songs/alan_walker_-_faded.mp3",
            },
            {
                id: 10,
                cover: "./images/alan_walker_-_the_drum.jpg",
                artist: "Alan Walker",
                title: "The drum",
                length: '3:09',
                src: "./songs/alan_walker_-_the_drum.mp3",
            },
            {
                id: 11,
                cover: "./images/alan_walker_-_the_spectre.jpg",
                artist: "Alan Walker",
                title: "The spectre",
                length: '3:13',
                src: "./songs/alan_walker_-_the_spectre.mp3",
            },
            {
                id: 12,
                cover: "./images/alan_walker_-_unity.jpg",
                artist: "Alan Walker",
                title: "Unity",
                length: '3:24',
                src: "./songs/alan_walker_-_unity.mp3",
            },
            
        ],
    },
    {
        album: 2,
        cover_album: "./images/katy_perry.png",        
        songs: [
            {
                id: 1,
                cover: "./images/katy_perry_-_dark_horse.jpg",
                artist: "Katy Perry",
                title: "Dark horse",
                length: '3:35',
                src: "./songs/katy_perry_-_dark_horse.mp3",
            },
            {
                id: 2,
                cover: "./images/katy_perry_-_firework.jpg",
                artist: "Katy Perry",
                title: "Firework",
                length: '3:48',
                src: "./songs/katy_perry_-_firework.mp3",
            },
            {
                id: 3,
                cover: "./images/katy_perry_-_hot_n_cold.jpg",
                artist: "Katy Perry",
                title: "Hot n cold",
                length: '3:40',
                src: "./songs/katy_perry_-_hot_n_cold.mp3",
            },
            {
                id: 4,
                cover: "./images/katy_perry_-_kissed.jpg",
                artist: "Katy Perry",
                title: "I kissed a girl",
                length: '3:01',
                src: "./songs/katy_perry_-_i_kissed_a_girl.mp3",
            },
            {
                id: 5,
                cover: "./images/katy_perry_-_roar.jpg",
                artist: "Katy Perry",
                title: "Roar",
                length: '3:44',
                src: "./songs/katy_perry_-_roar.mp3",
            },
            {
                id: 6,
                cover: "./images/katy_perry_-_dark_horse.jpg",
                artist: "Katy Perry",
                title: "Dark horse",
                length: '3:35',
                src: "./songs/katy_perry_-_dark_horse.mp3",
            },
            {
                id: 7,
                cover: "./images/katy_perry_-_firework.jpg",
                artist: "Katy Perry",
                title: "Firework",
                length: '3:48',
                src: "./songs/katy_perry_-_firework.mp3",
            },
            {
                id: 8,
                cover: "./images/katy_perry_-_hot_n_cold.jpg",
                artist: "Katy Perry",
                title: "Hot n cold",
                length: '3:40',
                src: "./songs/katy_perry_-_hot_n_cold.mp3",
            },
            {
                id: 9,
                cover: "./images/katy_perry_-_kissed.jpg",
                artist: "Katy Perry",
                title: "I kissed a girl",
                length: '3:01',
                src: "./songs/katy_perry_-_i_kissed_a_girl.mp3",
            },
            {
                id: 10,
                cover: "./images/katy_perry_-_roar.jpg",
                artist: "Katy Perry",
                title: "Roar",
                length: '3:44',
                src: "./songs/katy_perry_-_roar.mp3",
            },
        ],
    },
    {
        album: 3,
        cover_album: "./images/taylor_swift.png",        
        songs: [
            {
                id: 1,
                cover: "./images/taylor_swift_-_anti-hero.jpg",
                artist: "Taylor Swift",
                title: "Anti-hero",
                length: '3:23',
                src: "./songs/taylor_swift_-_anti-hero.mp3",
            },
            {
                id: 2,
                cover: "./images/taylor_swift_-_bad_blood.jpg",
                artist: "Taylor Swift",
                title: "Bad blood",
                length: '3:19',
                src: "./songs/taylor_swift_-_bad_blood.mp3",
            },
            {
                id: 3,
                cover: "./images/taylor_swift_-_blank.jpg",
                artist: "Taylor Swift",
                title: "Blank space",
                length: '3:51',
                src: "./songs/taylor_swift_-_blank_space.mp3",
            },
            {
                id: 4,
                cover: "./images/taylor_swift_-_gorgeous.jpg",
                artist: "Taylor Swift",
                title: "Gorgeous",
                length: '3:29',
                src: "./songs/taylor_swift_-_gorgeous.mp3",
            },
            {
                id: 5,
                cover: "./images/taylor_swift_-_haze.jpg",
                artist: "Taylor Swift",
                title: "Lavender haze",
                length: '3:25',
                src: "./songs/taylor_swift_-_lavender_haze.mp3",
            },
            {
                id: 6,
                cover: "./images/taylor_swift_-_shake.jpg",
                artist: "Taylor Swift",
                title: "Shake it off",
                length: '3:39',
                src: "./songs/taylor_swift_-_shake_it_off.mp3",
            },
            {
                id: 7,
                cover: "./images/taylor_swift_-_anti-hero.jpg",
                artist: "Taylor Swift",
                title: "Anti-hero",
                length: '3:23',
                src: "./songs/taylor_swift_-_anti-hero.mp3",
            },
            {
                id: 8,
                cover: "./images/taylor_swift_-_bad_blood.jpg",
                artist: "Taylor Swift",
                title: "Bad blood",
                length: '3:19',
                src: "./songs/taylor_swift_-_bad_blood.mp3",
            },
            {
                id: 9,
                cover: "./images/taylor_swift_-_blank.jpg",
                artist: "Taylor Swift",
                title: "Blank space",
                length: '3:51',
                src: "./songs/taylor_swift_-_blank_space.mp3",
            },
            {
                id: 10,
                cover: "./images/taylor_swift_-_gorgeous.jpg",
                artist: "Taylor Swift",
                title: "Gorgeous",
                length: '3:29',
                src: "./songs/taylor_swift_-_gorgeous.mp3",
            },
            {
                id: 11,
                cover: "./images/taylor_swift_-_haze.jpg",
                artist: "Taylor Swift",
                title: "Lavender haze",
                length: '3:25',
                src: "./songs/taylor_swift_-_lavender_haze.mp3",
            },
            {
                id: 12,
                cover: "./images/taylor_swift_-_shake.jpg",
                artist: "Taylor Swift",
                title: "Shake it off",
                length: '3:39',
                src: "./songs/taylor_swift_-_shake_it_off.mp3",
            },
        ],
    },
    {
        album: 4,
        cover_album: "./images/tiesto.png",
        songs: [
            {
                id: 1,
                cover: "./images/tiesto_-_all_nighter.jpg",
                artist: "Tiesto",
                title: "All nighter",
                length: '2:14',
                src: "./songs/tiesto_-_all_nighter.mp3",
            },
            {
                id: 2,
                cover: "./images/tiesto_-_shy.jpg",
                artist: "Tiesto",
                title: "Dont be shy",
                length: '2:20',
                src: "./songs/tiesto_-_dont_be_shy.mp3",
            },
            {
                id: 3,
                cover: "./images/tiesto_-_hot.jpg",
                artist: "Tiesto",
                title: "Hot in it",
                length: '2:10',
                src: "./songs/tiesto_-_hot_in_it.mp3",
            },
            {
                id: 4,
                cover: "./images/tiesto_-_lay_low.jpg",
                artist: "Tiesto",
                title: "Lay low",
                length: '2:33',
                src: "./songs/tiesto_-_lay_low.mp3",
            },
            {
                id: 5,
                cover: "./images/tiesto_-_business.jpg",
                artist: "Tiesto",
                title: "The business",
                length: '2:44',
                src: "./songs/tiesto_-_the_business.mp3",
            },
            {
                id: 6,
                cover: "./images/tiesto_-_all_nighter.jpg",
                artist: "Tiesto",
                title: "All nighter",
                length: '2:14',
                src: "./songs/tiesto_-_all_nighter.mp3",
            },
            {
                id: 7,
                cover: "./images/tiesto_-_shy.jpg",
                artist: "Tiesto",
                title: "Dont be shy",
                length: '2:20',
                src: "./songs/tiesto_-_dont_be_shy.mp3",
            },
            {
                id: 8,
                cover: "./images/tiesto_-_hot.jpg",
                artist: "Tiesto",
                title: "Hot in it",
                length: '2:10',
                src: "./songs/tiesto_-_hot_in_it.mp3",
            },
            {
                id: 9,
                cover: "./images/tiesto_-_lay_low.jpg",
                artist: "Tiesto",
                title: "Lay low",
                length: '2:33',
                src: "./songs/tiesto_-_lay_low.mp3",
            },
            {
                id: 10,
                cover: "./images/tiesto_-_business.jpg",
                artist: "Tiesto",
                title: "The business",
                length: '2:44',
                src: "./songs/tiesto_-_the_business.mp3",
            },
        ],
    },
];