const ALBOMS = [
   {
    id: 1,
    img: "images/albom1.jpg",
    name: "albom1",

    songs: [
        {
            id: 1,
            img: "images/cover-of-the-song-artik-asti.jpg",
            author: "Artik & Asti",
            name: "Кукла",
            minutes: "2:36",
            url: "songs/Artik & Asti - Кукла.mp3",
        },
        {
            id: 2,
            img: "images/cover-of-the-song.jpg",
            author: "Сергей Жуков",
            name: "Ты моя",
            minutes: "3:21",
            url: "songs/Сергей_Жуков_-_Ты_моя.mp3",
        },
        {
            id: 3,
            img: "images/cover-of-the-song.jpg",
            author: "Akmal' feat Юлианна Караулова",
            name: "Девочка,Не Прощай",
            minutes: "3:13",
            url: "songs/Akmal'_feat_Юлианна_Караулова_-_Девочка,_Не_Прощай.mp3",
        },
        {
            id: 4,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
        {
            id: 5,
            img: "images/cover-of-the-song.jpg",
            author: "Хабиб",
            name: "Ой Какая Ты",
            minutes: "2:18",
            url: "songs/Хабиб_-_Ой_Какая_Ты.mp3",
        },
        {
            id: 6,
            img: "images/cover-of-the-song.jpg",
            author: "Aquaneon",
            name: "Девчонка Со Двора",
            minutes: "2:00",
            url: "songs/Aquaneon_-_Девчонка_Со_Двора.mp3",
        },
    ],
   },
   {
    id: 2,
    img: "images/albom2.jpg",
    name: "albom2",
    songs: [
        {
            id: 7,
            img: "images/cover-of-the-song.jpg",
            author: "Сергей Жуков",
            name: "Ты моя",
            minutes: "3:21",
            url: "songs/Сергей_Жуков_-_Ты_моя.mp3",
        },
        {
            id: 8,
            img: "images/cover-of-the-song-artik-asti.jpg",
            author: "Artik & Asti",
            name: "Кукла",
            minutes: "2:36",
            url: "songs/Artik_&_Asti_-_Кукла.mp3",
        },
        {
            id: 9,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
        {
            id: 10,
            img: "images/cover-of-the-song.jpg",
            author: "Akmal' feat Юлианна Караулова",
            name: "Девочка,Не Прощай",
            minutes: "3:13",
            url: "songs/Akmal'_feat_Юлианна_Караулова_-_Девочка,_Не_Прощай.mp3",
        },
        {
            id: 11,
            img: "images/cover-of-the-song.jpg",
            author: "Aquaneon",
            name: "Девчонка Со Двора",
            minutes: "2:00",
            url: "songs/Aquaneon_-_Девчонка_Со_Двора.mp3",
        },
        {
            id: 12,
            img: "images/cover-of-the-song.jpg",
            author: "Хабиб",
            name: "Ой Какая Ты",
            minutes: "2:18",
            url: "songs/Хабиб_-_Ой_Какая_Ты.mp3",
        },
    ],
   },
   {
    id: 3,
    img: "images/albom3.jpg",
    name: "albom3",
    songs: [
        {
            id: 13,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
        {
            id: 14,
            img: "images/cover-of-the-song.jpg",
            author: "Aquaneon",
            name: "Девчонка Со Двора",
            minutes: "2:00",
            url: "songs/Aquaneon_-_Девчонка_Со_Двора.mp3",
        },
        {
            id: 15,
            img: "images/cover-of-the-song.jpg",
            author: "Akmal' feat Юлианна Караулова",
            name: "Девочка,Не Прощай",
            minutes: "3:13",
            url: "songs/Akmal'_feat_Юлианна_Караулова_-_Девочка,_Не_Прощай.mp3",
        },
        {
            id: 16,
            img: "images/cover-of-the-song.jpg",
            author: "Сергей Жуков",
            name: "Ты моя",
            minutes: "3:21",
            url: "songs/Сергей_Жуков_-_Ты_моя.mp3",
        },
        {
            id: 17,
            img: "images/cover-of-the-song-artik-asti.jpg",
            author: "Artik & Asti",
            name: "Кукла",
            minutes: "2:36",
            url: "songs/Artik_&_Asti_-_Кукла.mp3",
        },
        {
            id: 18,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
    ],
   },
   {
    id: 4,
    img: "images/albom4.jpg",
    name: "albom4",
    songs: [
        {
            id: 13,
            img: "images/cover-of-the-song.jpg",
            author: "Хабиб",
            name: "Ой Какая Ты",
            minutes: "2:18",
            url: "songs/Хабиб_-_Ой_Какая_Ты.mp3",
        },
        {
            id: 14,
            img: "images/cover-of-the-song.jpg",
            author: "Aquaneon",
            name: "Девчонка Со Двора",
            minutes: "2:00",
            url: "songs/Aquaneon_-_Девчонка_Со_Двора.mp3",
        },
        {
            id: 15,
            img: "images/cover-of-the-song-artik-asti.jpg",
            author: "Artik & Asti",
            name: "Кукла",
            minutes: "2:36",
            url: "songs/Artik_&_Asti_-_Кукла.mp3",
        },
        {
            id: 16,
            img: "images/cover-of-the-song.jpg",
            author: "Сергей Жуков",
            name: "Ты моя",
            minutes: "3:21",
            url: "songs/Сергей_Жуков_-_Ты_моя.mp3",
        },
        {
            id: 17,
            img: "images/cover-of-the-song.jpg",
            author: "Akmal' feat Юлианна Караулова",
            name: "Девочка,Не Прощай",
            minutes: "3:13",
            url: "songs/Akmal'_feat_Юлианна_Караулова_-_Девочка,_Не_Прощай.mp3",
        },
        {
            id: 18,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
    ],
   },
   {
    id: 5,
    img: "images/albom5.jpg",
    name: "albom5",
    songs: [
        {
            id: 13,
            img: "images/cover-of-the-song.jpg",
            author: "Bahh Tee feat Turken",
            name: "Путь К Тебе",
            minutes: "3:24",
            url: "songs/Bahh_Tee_feat_Turken_-_Путь_К_Тебе.mp3",
        },
        {
            id: 14,
            img: "images/cover-of-the-song.jpg",
            author: "Aquaneon",
            name: "Девчонка Со Двора",
            minutes: "2:00",
            url: "songs/Aquaneon_-_Девчонка_Со_Двора.mp3",
        },
        {
            id: 15,
            img: "images/cover-of-the-song-artik-asti.jpg",
            author: "Artik & Asti",
            name: "Кукла",
            minutes: "2:36",
            url: "songs/Artik_&_Asti_-_Кукла.mp3",
        },
        {
            id: 16,
            img: "images/cover-of-the-song.jpg",
            author: "Сергей Жуков",
            name: "Ты моя",
            minutes: "3:21",
            url: "songs/Сергей_Жуков_-_Ты_моя.mp3",
        },
        {
            id: 17,
            img: "images/cover-of-the-song.jpg",
            author: "Akmal' feat Юлианна Караулова",
            name: "Девочка,Не Прощай",
            minutes: "3:13",
            url: "songs/Akmal'_feat_Юлианна_Караулова_-_Девочка,_Не_Прощай.mp3",
        },
        {
            id: 18,
            img: "images/cover-of-the-song.jpg",
            author: "Хабиб",
            name: "Ой Какая Ты",
            minutes: "2:18",
            url: "songs/Хабиб_-_Ой_Какая_Ты.mp3",
        },
    ],
   },
];








  