name: CSS Linter

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm ci --no-audit
      - run: git fetch origin master:refs/remotes/origin/master
      - name: Verify diff files
        run: bash .github/lint-css.sh
