name: Pull Request Name

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, reopened, synchronize]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: rm -rf package.json package-lock.json
      - run: npm i --no-audit @actions/core @actions/github
      - name: Verify Pull Request Name
        uses: ./.github/actions/pull-request-name
